before_install:
  - sudo apt-get install cmake

before_script:
  - cmake -G "Unix Makefiles" -DASSIMP_ENABLE_BOOST_WORKAROUND=YES -DASSIMP_NO_EXPORT=$TRAVIS_NO_EXPORT

env:
  - TRAVIS_NO_EXPORT=YES
  - TRAVIS_NO_EXPORT=NO

language: cpp

compiler:
  - gcc
  - clang

script: make



